### ISSUE TITLE
Assertion in Demarshaling::is_valid() while parsing return data if using dbus-cxx with bluez

### ISSUE THREAD

**Issue by stefschu1510** [dbus-cxx/dbus-cxx#105]
Hello,
I tried to use dbus-cxx to implement my own Gatt-Server.
Unfortunately, if throws an assertion when I try to execute a "GetManagedObjects":

![image](https://user-images.githubusercontent.com/51327575/193581881-8abdc98c-57b1-486c-a497-0fc813d867f2.png)

It looks like the method call itself is correct and working, and the method return can be seen using dbus-monitor:

```
$ sudo dbus-monitor --system "destination='org.bluez'" "sender='org.bluez'"
signal time=1664801203.520492 sender=org.freedesktop.DBus -> destination=:1.238 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.238"
signal time=1664801203.520543 sender=org.freedesktop.DBus -> destination=:1.238 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.238"
method call time=1664801213.799140 sender=:1.239 -> destination=org.bluez serial=6 path=/; interface=org.freedesktop.DBus.ObjectManager; member=GetManagedObjects
method return time=1664801213.799314 sender=:1.19 -> destination=:1.239 serial=146 reply_serial=6
   array [
      dict entry(
         object path "/org/bluez"
         array [
            dict entry(
               string "org.freedesktop.DBus.Introspectable"
               array [
               ]
            )
            dict entry(
               string "org.bluez.AgentManager1"
               array [
               ]
            )
            dict entry(
               string "org.bluez.ProfileManager1"
               array [
               ]
            )
            dict entry(
               string "org.bluez.HealthManager1"
               array [
               ]
            )
         ]
      )
      dict entry(
         object path "/org/bluez/hci0"
         array [
            dict entry(
               string "org.freedesktop.DBus.Introspectable"
               array [
               ]
            )
            dict entry(
               string "org.bluez.Adapter1"
               array [
                  dict entry(
                     string "Address"
                     variant                         string "00:1A:7D:DA:71:13"
                  )
                  dict entry(
                     string "AddressType"
                     variant                         string "public"
                  )
                  dict entry(
                     string "Name"
                     variant                         string "phidias"
                  )
                  dict entry(
                     string "Alias"
                     variant                         string "phidias"
                  )
                  dict entry(
                     string "Class"
                     variant                         uint32 2883844
                  )
                  dict entry(
                     string "Powered"
                     variant                         boolean true
                  )
                  dict entry(
                     string "Discoverable"
                     variant                         boolean false
                  )
                  dict entry(
                     string "DiscoverableTimeout"
                     variant                         uint32 180
                  )
                  dict entry(
                     string "Pairable"
                     variant                         boolean false
                  )
                  dict entry(
                     string "PairableTimeout"
                     variant                         uint32 0
                  )
                  dict entry(
                     string "Discovering"
                     variant                         boolean false
                  )
                  dict entry(
                     string "UUIDs"
                     variant                         array [
                           string "00001112-0000-1000-8000-00805f9b34fb"
                           string "0000110e-0000-1000-8000-00805f9b34fb"
                           string "00001200-0000-1000-8000-00805f9b34fb"
                           string "0000110b-0000-1000-8000-00805f9b34fb"
                           string "00001108-0000-1000-8000-00805f9b34fb"
                           string "0000110c-0000-1000-8000-00805f9b34fb"
                           string "00001800-0000-1000-8000-00805f9b34fb"
                           string "0000110a-0000-1000-8000-00805f9b34fb"
                           string "00001801-0000-1000-8000-00805f9b34fb"
                           string "0000180a-0000-1000-8000-00805f9b34fb"
                        ]
                  )
                  dict entry(
                     string "Modalias"
                     variant                         string "usb:v1D6Bp0246d0537"
                  )
                  dict entry(
                     string "Roles"
                     variant                         array [
                           string "central"
                           string "peripheral"
                        ]
                  )
               ]
            )
            dict entry(
               string "org.freedesktop.DBus.Properties"
               array [
               ]
            )
            dict entry(
               string "org.bluez.GattManager1"
               array [
               ]
            )
            dict entry(
               string "org.bluez.LEAdvertisingManager1"
               array [
                  dict entry(
                     string "ActiveInstances"
                     variant                         byte 0
                  )
                  dict entry(
                     string "SupportedInstances"
                     variant                         byte 5
                  )
                  dict entry(
                     string "SupportedIncludes"
                     variant                         array [
                           string "tx-power"
                           string "appearance"
                           string "local-name"
                        ]
                  )
               ]
            )
            dict entry(
               string "org.bluez.Media1"
               array [
               ]
            )
            dict entry(
               string "org.bluez.NetworkServer1"
               array [
               ]
            )
         ]
      )
   ]
```
However, there seems to be a problem during the deserialization of the method return data. During debugging I have seen that all the data is parsed correctly, and MessageIterator::get_dict() is called again and again until all data is processed. But after parsing the last dict entry, it tries to parse more data, which is not available.

No assertion ca be seen if I do not connect my bluetooth-dongle to the PC - of course the returned data is only a few bytes in that case:

```
$ sudo dbus-monitor --system "destination='org.bluez'" "sender='org.bluez'"
signal time=1664801592.944594 sender=org.freedesktop.DBus -> destination=:1.243 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.243"
signal time=1664801592.944615 sender=org.freedesktop.DBus -> destination=:1.243 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.243"
method call time=1664801634.389928 sender=:1.244 -> destination=org.bluez serial=6 path=/; interface=org.freedesktop.DBus.ObjectManager; member=GetManagedObjects
method return time=1664801634.389977 sender=:1.19 -> destination=:1.244 serial=153 reply_serial=6
   array [
      dict entry(
         object path "/org/bluez"
         array [
            dict entry(
               string "org.freedesktop.DBus.Introspectable"
               array [
               ]
            )
            dict entry(
               string "org.bluez.AgentManager1"
               array [
               ]
            )
            dict entry(
               string "org.bluez.ProfileManager1"
               array [
               ]
            )
            dict entry(
               string "org.bluez.HealthManager1"
               array [
               ]
            )
         ]
      )
   ]
```

I guess the issue can be simply reproduced with other bluetooth adapters as well using this sample main.cpp:

[main.zip](https://github.com/dbus-cxx/dbus-cxx/files/9697683/main.zip)

I'm using the latest version 2.3.0 on Debian Linux 11.

Best Regards,

Stefan

**Comment by rm5248** [comment]
How did you test this without the bluetooth dongle?  I don't get a crash.

This is probably related to the rather ridiculous definition of this method: `org.freedesktop.DBus.ObjectManager.GetManagedObjects (out ARRAY of DICT_ENTRY<OBJPATH,ARRAY of DICT_ENTRY<STRING,ARRAY of DICT_ENTRY<STRING,VARIANT>>> objpath_interfaces_and_properties);`

That should be: `a{o,a{s,a{s,v}}}`

**Comment by stefschu1510** [comment]
Yes, very likely this is related to the signature of this method.
As mentioned, I could not reproduce any issue without bluetooth dongle - but in that case the 
`org.freedesktop.DBus.ObjectManager.GetManagedObjects (out ARRAY of DICT_ENTRY<OBJPATH,ARRAY of DICT_ENTRY<STRING,ARRAY of DICT_ENTRY<STRING,VARIANT>>> objpath_interfaces_and_properties)` 
is missing. So finally I could reproduce it only if a Bluetooth dongle is connected.

Is there anything I can do to find the root cause? Activate some logging, checking the content of some variables at the time the assert is hit?

**Comment by rm5248** [comment]
You could try enabling the logging, but I don't know if that would show you anything.  Take a look at the methods in the [utility header](https://github.com/dbus-cxx/dbus-cxx/blob/dd21ce5c0967d719420619ebdf8aa0c80fbe1979/dbus-cxx/utility.h#L88) to enable the logging.

Probably the most useful thing to do would be to create a standalone program that sends back a message with the correct signature so that we can test this without needing to use Bluez.  If you feel up to it, turning this into a unit test would be helpful as well(add a test to the unit-tests/datatests.cpp file)

**Comment by stefschu1510** [comment]
Sorry, I'm an newbie to the DBus protocol. I have tried to create a test with this complex signature.
Unfortunately, it fails, and I get a DBus::ErrorNoReply. I do not understand why, as I can see from the test that the appropriate message is called:

```
0xC67B3700 DBus.priv.SendmsgTransport [TRACE] - Going to send the following bytes: 
000000: 42 02 00 01 00 00 00 4b   00 00 00 03 00 00 00 2e   B......K  ........
000010: 05 01 75 00 00 00 00 06   06 01 73 00 00 00 00 04   ..u.....  ..s.....
000020: 3a 31 2e 31 00 00 00 00   08 01 67 00 10 61 61 7b   :1.1....  ..g..aa{
000030: 6f 61 61 7b 73 61 61 7b   73 76 7d 7d 7d 00 00 00   oaa{saa{  sv}}}...
000040: 00 00 00 47 00 00 00 3f   00 00 00 00 00 00 00 06   ...G...?  ........
000050: 2f 70 74 65 73 74 00 00   00 00 00 2f 00 00 00 27   /ptest..  .../...'
000060: 00 00 00 00 00 00 00 02   72 31 00 00 00 00 00 1b   ........  r1......
000070: 00 00 00 13 00 00 00 00   00 00 00 02 73 31 00 01   ........  ....s1..
000080: 73 00 00 00 00 00 00 02   76 31 00                  s.......  v1.
(/home/stefan/projects/dbus-cxx/dbus-cxx/sendmsgtransport.cpp:297)

```

However, I also do not understand why my generated signature seen in the message is `aa{o,aa{s,aa{s,v}}}` instead of `a{o,a{s,a{s,v}}}`.
You could try my branch at

https://github.com/stefschu1510/dbus-cxx/tree/issue105_complex_message

**Comment by rm5248** [comment]
The reason the signature is wrong is because of how maps are defined.  A map signature is an array followed by the key/value types(e.g. `a{s,v}`).  An array also starts with `a`, but it contains only one type(e.g. `ai`).  This is a rather confusing part of the spec and it has tripped me up a few times as well.

With that being said, your type of:
```
std::shared_ptr<DBus::MethodProxy<std::vector<std::map<DBus::Path, std::vector<std::map<std::string, std::vector<std::map<std::string, DBus::Variant>>>>>>()>> int_custom_method_proxy3;
```
should just need to be changed to:
```
std::shared_ptr<DBus::MethodProxy<std::map<DBus::Path, std::map<std::string,std::map<std::string, DBus::Variant>>>()>> int_custom_method_proxy3;
```

I'll have a chance to take a look at it sometime in the coming days.

**Comment by stefschu1510** [comment]
Thanks for the hint. I have updated the types, and the signature is correct now.
In addition, the test itself is working now and I do not get any longer the DBus::ErrorNoReply. So I can play now play with this test and extend it to see hopefully the same assertion as with my real bluez project.

**Comment by rm5248** [comment]
I haven't tracked down the problem quite yet, but I do have a branch with appropriate tests that are failing at this point: https://github.com/dbus-cxx/dbus-cxx/tree/issue-105

There seems to be a problem with demarshaling complex variants inside of a map of a map of a map.

**Comment by rm5248** [comment]
I think I know the root cause, but not how to fix it yet: because of the way variants are implemented, this will sometimes work and sometimes not work.  Because variants do not know where exactly they are marshalled, they try to marshal themselves.  For example, if the variant has a map with two entries, it will internally marshal the bytes as such(hex):
```
00 00 00 08 00 00 00 00 00 00 00 05 00 00 00 06
  length   |  padding  |   key    |  value
```

This is because dict entries have to be on an 8-byte boundary.

HOWEVER, depending on where these bytes are inserted into the final message, the padding MAY or MAY NOT be needed, depending on where the end of 'length' ends up.  If the end of 'length' ends on a 4-byte boundary, the padding is needed, so there aren't any problems.  If the end of 'length' ends on an 8-byte boundary, well now the dict entry is starting on a 4-byte boundary instead of the specified 8-byte boundary.

**Comment by rm5248** [comment]
I have fixed the padding issue with variants and maps so that at least the tests no longer fail and you do not get kicked off of the bus due to sending invalid data.  I don't think that would fix anything on the _parsing_ side, but maybe it does?  Would you be able to check the branch and see if it now works for you?

If it is still broken, we will need to add more data to the test in order to trigger this behavior to fix it.

**Comment by stefschu1510** [comment]
Thanks for investigation. I tried the branch. Unfortunately, it still does not work with my bluez code. I get the same assertion as before.
However, according to your remarks indeed the different padding and alignment might be the issue. I will hopefully find some time tomorrow to do also some testing on that branch.

**Comment by rm5248** [comment]
If you can capture the offending message with dbus-monitor as a pcap file(`dbus-monitor --pcap`) it should be easy to create a test to parse that specific message and figure out why it is breaking.

**Comment by stefschu1510** [comment]
> If you can capture the offending message with dbus-monitor as a pcap file(`dbus-monitor --pcap`) it should be easy to create a test to parse that specific message and figure out why it is breaking.

In fact I also had the idea somehow to dump/trace the GetManagedObjects response and to add some test for parsing this particular message only. I was not aware of the capability of dbus-monitor to generate the pcap format.
I just created a pcap file with the GetManagedObjects command and response.
[GetManagedObjects.zip](https://github.com/dbus-cxx/dbus-cxx/files/9763319/GetManagedObjects.zip)

**Comment by stefschu1510** [comment]
I have extracted the response to a bin-file (GetManagedObjectsResponse.bin) and extended the messageiteratortests with a test to parse the response message. You can find the changes at my branch:

https://github.com/stefschu1510/dbus-cxx/tree/issue105_complex_message

The bin-file is copied to build/unit-tests,  so currently it is required to execute the test within the build/unit-test folder:

`~/projects/dbus-cxx/build/unit-tests$ ./test-messageiterator map_map_map-3`

As expected, it throws exactly the same debug logs and assertion as for my real scenario.

```
...
0x1C88B740 DBus.Signature [TRACE] - Signature 'as' is valid(/home/stefan/projects/dbus-cxx/dbus-cxx/signature.cpp:299)
0x1C88B740 DBus.Signature [TRACE] - Signature 'as' is valid(/home/stefan/projects/dbus-cxx/dbus-cxx/signature.cpp:299)
0x1C88B740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 1240 array len: 47(/home/stefan/projects/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x1C88B740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 1316 array len: 0(/home/stefan/projects/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x1C88B740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 1356 array len: 0(/home/stefan/projects/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
test-messageiterator: /home/stefan/projects/dbus-cxx/dbus-cxx/demarshaling.cpp:309: void DBus::Demarshaling::is_valid(uint32_t): Assertion `( m_priv->m_dataPos + bytesWanted ) <= m_priv->m_dataLen' failed.
Aborted
```

I did not yet find the root cause for the crash. :-(

**Comment by rm5248** [comment]
Thanks for the dump, that is very useful.

I don't have an exact cause yet, but this looks very suspicious:
```
0x839E4740 DBus.Message [TRACE] - Following message created from the data: DBus::Message = [ReturnMessage
  Message length: 1360
  Endianess: Little
  Serial: 2385
  Headers:
    Reply Serial: 6
    Destination: :1.347
    Sender: :1.6
    Signature: DBus::Signature[a{oa{sa{sv}}}]
](/home/robert/dbus-cxx/dbus-cxx/message.cpp:354)
0x839E4740 DBus.Signature [TRACE] - Signature 'a{oa{sa{sv}}}' is valid(/home/robert/dbus-cxx/dbus-cxx/signature.cpp:299)
0x839E4740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 4 array len: 1352 array end pos: 1356(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x839E4740 DBus.MessageIterator [DEBUG] - Extracting dict entry(a{oa{sa{sv}}})(/home/robert/dbus-cxx/dbus-cxx/messageiterator.h:246)
0x839E4740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 28 array len: 120 array end pos: 148(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x839E4740 DBus.MessageIterator [DEBUG] - Extracting dict entry(a{sa{sv}})(/home/robert/dbus-cxx/dbus-cxx/messageiterator.h:246)
0x839E4740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 76 array len: 0 array end pos: 76(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x839E4740 DBus.MessageIterator [TRACE] - Array extraction done.  new position: 76(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:116)
0x839E4740 DBus.MessageIterator [DEBUG] - Extracting dict entry(a{sa{sv}})(/home/robert/dbus-cxx/dbus-cxx/messageiterator.h:246)
0x839E4740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 112 array len: 0 array end pos: 112(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x839E4740 DBus.MessageIterator [TRACE] - Array extraction done.  new position: 112(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:116)
0x839E4740 DBus.MessageIterator [DEBUG] - Extracting dict entry(a{sa{sv}})(/home/robert/dbus-cxx/dbus-cxx/messageiterator.h:246)
0x839E4740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 148 array len: 0 array end pos: 148(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
0x839E4740 DBus.MessageIterator [TRACE] - Array extraction done.  new position: 148(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:116)
0x839E4740 DBus.MessageIterator [TRACE] - Array extraction done.  new position: 148(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:116)
0x839E4740 DBus.MessageIterator [TRACE] - Array extraction done.  new position: 148(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:116)
0x839E4740 DBus.MessageIterator [DEBUG] - Extracting dict entry(a{oa{sa{sv}}})(/home/robert/dbus-cxx/dbus-cxx/messageiterator.h:246)
0x839E4740 DBus.MessageIterator [TRACE] - Extracting array.  new position: 176 array len: 1184 array end pos: 1360(/home/robert/dbus-cxx/dbus-cxx/messageiterator.cpp:57)
```

The size of the message is 1360 bytes, the first array we try to extract should end on byte 1356, and then a few lines later we have another array that should end on byte 1360.  So clearly something is very confused here, but I'm not sure what at the moment.

**Comment by rm5248** [comment]
I think I have just fixed it(the test now passes).  The fix was very simple, just making sure the iterator is still valid before we try to extract the next value in the array.  Let me know if it now works properly for you.

**Comment by stefschu1510** [comment]
Great job. I can confirm that this issue is solved with this simple fix.
I can continue now with my application. Thanks a lot. :-)
